/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiActivityGet$Json } from '../fn/reward-activity/api-activity-get-json';
import { ApiActivityGet$Json$Params } from '../fn/reward-activity/api-activity-get-json';
import { apiActivityGet$Plain } from '../fn/reward-activity/api-activity-get-plain';
import { ApiActivityGet$Plain$Params } from '../fn/reward-activity/api-activity-get-plain';
import { apiActivityPost$Json } from '../fn/reward-activity/api-activity-post-json';
import { ApiActivityPost$Json$Params } from '../fn/reward-activity/api-activity-post-json';
import { apiActivityPost$Plain } from '../fn/reward-activity/api-activity-post-plain';
import { ApiActivityPost$Plain$Params } from '../fn/reward-activity/api-activity-post-plain';
import { RewardActivity } from '../models/reward-activity';

@Injectable({ providedIn: 'root' })
export class RewardActivityApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiActivityGet()` */
  static readonly ApiActivityGetPath = '/api/activity';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiActivityGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiActivityGet$Plain$Response(params?: ApiActivityGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RewardActivity>>> {
    return apiActivityGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiActivityGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiActivityGet$Plain(params?: ApiActivityGet$Plain$Params, context?: HttpContext): Observable<Array<RewardActivity>> {
    return this.apiActivityGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<RewardActivity>>): Array<RewardActivity> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiActivityGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiActivityGet$Json$Response(params?: ApiActivityGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RewardActivity>>> {
    return apiActivityGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiActivityGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiActivityGet$Json(params?: ApiActivityGet$Json$Params, context?: HttpContext): Observable<Array<RewardActivity>> {
    return this.apiActivityGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<RewardActivity>>): Array<RewardActivity> => r.body)
    );
  }

  /** Path part for operation `apiActivityPost()` */
  static readonly ApiActivityPostPath = '/api/activity';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiActivityPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiActivityPost$Plain$Response(params?: ApiActivityPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<RewardActivity>> {
    return apiActivityPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiActivityPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiActivityPost$Plain(params?: ApiActivityPost$Plain$Params, context?: HttpContext): Observable<RewardActivity> {
    return this.apiActivityPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<RewardActivity>): RewardActivity => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiActivityPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiActivityPost$Json$Response(params?: ApiActivityPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<RewardActivity>> {
    return apiActivityPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiActivityPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiActivityPost$Json(params?: ApiActivityPost$Json$Params, context?: HttpContext): Observable<RewardActivity> {
    return this.apiActivityPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<RewardActivity>): RewardActivity => r.body)
    );
  }

}
