/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Reward } from '../../models/reward';

export interface ApiRewardRewardIdGet$Plain$Params {
  rewardId: number;
}

export function apiRewardRewardIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiRewardRewardIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Reward>> {
  const rb = new RequestBuilder(rootUrl, apiRewardRewardIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('rewardId', params.rewardId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Reward>;
    })
  );
}

apiRewardRewardIdGet$Plain.PATH = '/api/reward/{rewardId}';
