/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Reward } from '../../models/reward';

export interface ApiRewardGet$Plain$Params {
}

export function apiRewardGet$Plain(http: HttpClient, rootUrl: string, params?: ApiRewardGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Reward>>> {
  const rb = new RequestBuilder(rootUrl, apiRewardGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Reward>>;
    })
  );
}

apiRewardGet$Plain.PATH = '/api/reward';
