/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Reward } from '../../models/reward';

export interface ApiRewardChildChildIdGet$Json$Params {
  childId: number;
}

export function apiRewardChildChildIdGet$Json(http: HttpClient, rootUrl: string, params: ApiRewardChildChildIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Reward>>> {
  const rb = new RequestBuilder(rootUrl, apiRewardChildChildIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('childId', params.childId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Reward>>;
    })
  );
}

apiRewardChildChildIdGet$Json.PATH = '/api/reward/child/{childId}';
