/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RewardActivity } from '../models/reward-activity';
export interface Reward {
  activity?: RewardActivity;
  comment?: string | null;
  defaultMinutes?: number;
  id?: number;
  issuedOn?: string;
}
