/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RewardUsageRequest {
  comment?: string | null;
  minutes?: number;
  usedOn?: string | null;
}
