/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RewardActivity {
  description?: string | null;
  id?: number;
  minutes?: number;
  name: string | null;
}
