/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RewardRequest {
  activityId?: number | null;
  comment?: string | null;
  issuedOn?: string | null;
  minutes?: number;
}
