/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserInfo {
  id?: string | null;
  name?: string | null;
  profileImageUrl?: string | null;
}
