/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Child } from '../models/child';
export interface User {
  children?: Array<Child> | null;
  created?: string;
  eMail: string | null;
  fullName: string | null;
  id?: number;
  lastActive?: string;
  oAuthId?: string | null;
  username: string | null;
}
