/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RewardActivity } from '../../models/reward-activity';

export interface ApiActivityGet$Plain$Params {
}

export function apiActivityGet$Plain(http: HttpClient, rootUrl: string, params?: ApiActivityGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RewardActivity>>> {
  const rb = new RequestBuilder(rootUrl, apiActivityGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RewardActivity>>;
    })
  );
}

apiActivityGet$Plain.PATH = '/api/activity';
