/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RewardActivity } from '../../models/reward-activity';

export interface ApiActivityPost$Json$Params {
      body?: RewardActivity
}

export function apiActivityPost$Json(http: HttpClient, rootUrl: string, params?: ApiActivityPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<RewardActivity>> {
  const rb = new RequestBuilder(rootUrl, apiActivityPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RewardActivity>;
    })
  );
}

apiActivityPost$Json.PATH = '/api/activity';
