/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Child } from '../../models/child';

export interface ApiActivityActivityIdChildChildIdPost$Plain$Params {
  childId: number;
  rewardActivityId?: number;
  activityId: string;
}

export function apiActivityActivityIdChildChildIdPost$Plain(http: HttpClient, rootUrl: string, params: ApiActivityActivityIdChildChildIdPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Child>> {
  const rb = new RequestBuilder(rootUrl, apiActivityActivityIdChildChildIdPost$Plain.PATH, 'post');
  if (params) {
    rb.path('childId', params.childId, {});
    rb.query('rewardActivityId', params.rewardActivityId, {});
    rb.path('activityId', params.activityId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Child>;
    })
  );
}

apiActivityActivityIdChildChildIdPost$Plain.PATH = '/api/activity/{activityId}/child/{childId}';
