/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RewardActivity } from '../../models/reward-activity';

export interface ApiActivityActivityIdGet$Plain$Params {
  activityId: number;
}

export function apiActivityActivityIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiActivityActivityIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<RewardActivity>> {
  const rb = new RequestBuilder(rootUrl, apiActivityActivityIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('activityId', params.activityId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RewardActivity>;
    })
  );
}

apiActivityActivityIdGet$Plain.PATH = '/api/activity/{activityId}';
