/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RewardUsage } from '../../models/reward-usage';

export interface ApiUsageUsageIdGet$Plain$Params {
  usageId: number;
}

export function apiUsageUsageIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiUsageUsageIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<RewardUsage>> {
  const rb = new RequestBuilder(rootUrl, apiUsageUsageIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('usageId', params.usageId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RewardUsage>;
    })
  );
}

apiUsageUsageIdGet$Plain.PATH = '/api/usage/{usageId}';
