/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Child } from '../../models/child';
import { RewardRequest } from '../../models/reward-request';

export interface ApiChildChildIdRewardPost$Json$Params {
  childId: number;
      body?: RewardRequest
}

export function apiChildChildIdRewardPost$Json(http: HttpClient, rootUrl: string, params: ApiChildChildIdRewardPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Child>> {
  const rb = new RequestBuilder(rootUrl, apiChildChildIdRewardPost$Json.PATH, 'post');
  if (params) {
    rb.path('childId', params.childId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Child>;
    })
  );
}

apiChildChildIdRewardPost$Json.PATH = '/api/child/{childId}/reward';
