/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Child } from '../../models/child';
import { ChildCreationRequest } from '../../models/child-creation-request';

export interface ApiChildPost$Json$Params {
      body?: ChildCreationRequest
}

export function apiChildPost$Json(http: HttpClient, rootUrl: string, params?: ApiChildPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Child>> {
  const rb = new RequestBuilder(rootUrl, apiChildPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Child>;
    })
  );
}

apiChildPost$Json.PATH = '/api/child';
