/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Child } from '../../models/child';
import { RewardUsageRequest } from '../../models/reward-usage-request';

export interface ApiChildChildIdUsagePost$Plain$Params {
  childId: number;
      body?: RewardUsageRequest
}

export function apiChildChildIdUsagePost$Plain(http: HttpClient, rootUrl: string, params: ApiChildChildIdUsagePost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Child>> {
  const rb = new RequestBuilder(rootUrl, apiChildChildIdUsagePost$Plain.PATH, 'post');
  if (params) {
    rb.path('childId', params.childId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Child>;
    })
  );
}

apiChildChildIdUsagePost$Plain.PATH = '/api/child/{childId}/usage';
