/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Child } from '../../models/child';

export interface ApiChildChildIdGet$Json$Params {
  childId: number;
}

export function apiChildChildIdGet$Json(http: HttpClient, rootUrl: string, params: ApiChildChildIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Child>> {
  const rb = new RequestBuilder(rootUrl, apiChildChildIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('childId', params.childId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Child>;
    })
  );
}

apiChildChildIdGet$Json.PATH = '/api/child/{childId}';
