/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChildInfo } from '../../models/child-info';

export interface ApiChildInfosGet$Plain$Params {
}

export function apiChildInfosGet$Plain(http: HttpClient, rootUrl: string, params?: ApiChildInfosGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ChildInfo>>> {
  const rb = new RequestBuilder(rootUrl, apiChildInfosGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ChildInfo>>;
    })
  );
}

apiChildInfosGet$Plain.PATH = '/api/child/infos';
